spring:
  application:
    name: What Will You Be Backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/what_will_you_be?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

jwt:
  secret:
    key: bXlTdXBlclNlY3JldEtleTEyMzQ1Njc4OTAhQCMkJV4=
  token:
    expiration: 1800000 # 30분 (1000ms * 60 * 30)

api:
  python:
    url: http://127.0.0.1:8000